PM_ERROR(NONE,  "No error")
PM_ERROR(NOMEM, "No more memory")
PM_ERROR(XDR, "XDR failed")
PM_ERROR(NOPAM, "Application is not started by PAM")
PM_ERROR(INIT, "Fail to initialize PM library internal")
PM_ERROR(SYSCALL, "Error in System Call")
