#!/bin/sh
for i in 1 3 4 5 8
do
     if [ -d man$i ]; then
       if [   -d $1/cat$i ] ; then 
         rm -r $1/cat$i
       fi
        mkdir $1/cat$i
        for n in `ls man$i/*.$i | sed -e 's/man[13458]\// /g' | sed -e 's/\.[13458]//g'`
        do
            echo "nroff -man man$i/$n.$i > $1/cat$i/$n"
            nroff -man man$i/$n.$i > $1/cat$i/$n
            pack -f $1/cat$i/$n
        done
     fi
done
 

