# Makefile for ODBC added by iRODS installation scripts
all install installdirs uninstall dep depend distprep clean distclean maintainer-clean:
	@$(MAKE) -C /usr/users/ga002/tyrrells/Projects/iRODS-3.3.1/postgres/postgresql-9.3.2/src/interfaces/odbc/unixODBC-2.2.12
