######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 27 12:08:33 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

LIBS += -lodbc

# Input
HEADERS += maindialog.h
INTERFACES += qt_about.ui qt_maindialog.ui
SOURCES += maindialog.cpp ODBCStats.cpp
